[build-system]
requires = ["scikit-build-core >= 0.11"]
build-backend = "scikit_build_core.build"

[project]
name = "QtBridge"
version = "0.0.1"
requires-python = ">=3.9, <=3.15"
description = "Python package providing the backend Python API to interact with QML frontend"
authors = [
    { name = "QtBridge Python Team", email = "qtbridge@qt.io" },
]
license = "LicenseRef-Commercial OR LGPL-3.0-only"
dependencies = [
    "shiboken6 > 6.9",
    "PySide6-Essentials > 6.9",
    "numpy"
]

[tool.scikit-build]
cmake.version = ">=3.18"
cmake.source-dir = "."
build-dir = "build/{wheel_tag}"
build.verbose = true
wheel.py-api = "cp39" # align with PySide6 and shiboken6
wheel.cmake = true
build.requires = [
    "shiboken6>=6.11,<6.12",
    "PySide6-Essentials>=6.11,<6.12",
]
wheel.exclude = [
    "*.cpp",
    "*.h",
    "CMakeLists.txt",
    "*.cmake",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-qt",
    "pytest-forked>=1.5; sys_platform == 'linux'",
    "mypy",
    "black",
    "flake8"
]
# this enables pip install -e ".[table]"
table = [
    "polars"
]
docs = [
    "sphinx>=7.3,<9",  # getting rid of warning
    "furo>=2025.12.19",
    "myst-parser>=3.0",
    "sphinx-copybutton>=0.5",
    "sphinx-autodoc-typehints>=2.0",
]


[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v --tb=short"
qt_api = "pyside6"
markers = [
    "forked: run test in a forked subprocess (no-op on macOS)",
]

[tool.scikit-build.cmake.define]
QT_NO_PRIVATE_MODULE_WARNING = "ON"
